version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    hostname: postgres-db

  tomcat:
    image: ue1104-backend-api:1.3.0
    ports:
      - 80:8080
    hostname: spring-web
    depends_on:
      - postgres      
